map $uri $new_content_type {
    default "text/html";
    ~*\.json$ "application/json";
    ~*\.css$ "text/css";
    ~*\.js$ "application/javascript";
    ~*\.woff2?$ "font/woff2";
    ~*\.png$ "image/png";
}

server {
    listen 8080;
    server_name localhost;

    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    if_modified_since off;
    expires off;
    etag off;

    location = / {
        return 301 $scheme://$http_host/index.html;
    }

    location / {
        proxy_pass http://minio:9000/dbt-docs/;
        proxy_set_header Host $http_host;
        proxy_set_header User-Agent "minio-go/7.0.0";
        
        proxy_redirect http://minio:9000/ /;
        proxy_redirect http://$host:9000/ /;
        
        proxy_hide_header Content-Type;
        proxy_hide_header Content-Disposition;
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-id-2;
        add_header Content-Type $new_content_type;
    }
}